#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  frontButton,    sensorTouch)
#pragma config(Sensor, dgtl2,  backButton,     sensorTouch)
#pragma config(Sensor, dgtl3,  armButton,      sensorTouch)
#pragma config(Motor,  port1,           frontRight,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////
//					Code made by Matthew V. Ballou	 			//
//   Science Fair Project of 2018, Ballou Bros.   //
//								PROSTHETIC HAND									//
////////////////////////////////////////////////////

//Task declarations
task main();
task display();

//Arm direction enum declaration

enum dir {

	open 				= 0,
	close 			= 1,
	stopmoving 	= 2,

};

//Different modes enum declaration

enum mode {

	button 			= 0,
	controller 	= 1,
	demo 				= 2,
	noMode			= 3,

};

//LCD Button enum declaration

enum LCDButton {

	left				=	1,
	center			= 2,
	right				= 4,

};

//Mode function declarations

mode robotMode = noMode;

//LCD Display functions

void clearLCD() {

	clearLCDLine(0);
	clearLCDLine(1);

}

//Arm status functions

bool isArmOpen() {

	if(SensorValue[frontButton] == 1) {return true;}
	else{return false;}

}

bool isArmClosed() {

	if(SensorValue[backButton] == 1) {return true;}
	else{return false;}

}

//Motor power functions

void powerMotorRight(dir direction) {

	if(direction == open) {
		motor[frontRight] =  122;
		motor[backRight] 	=  122;
	}
	else if(direction == close) {
		motor[frontRight] = -122;
		motor[backRight] 	= -122;
	}
	else {
		motor[frontRight] =  0;
		motor[backRight] 	=  0;
	}

}

void powerMotorLeft(dir direction) {

	if(direction == open) {
		motor[frontLeft] 	=  122;
		motor[backLeft] 	=  122;
	}
	else if(direction == close) {
		motor[frontLeft] 	= -122;
		motor[backLeft] 	= -122;
	}
	else {
		motor[frontLeft] 	=  0;
		motor[backLeft] 	=  0;
	}

}

//Operation functions

void openArm() {

	while(!isArmOpen()) {
		powerMotorLeft(open);
		powerMotorRight(open);
	}

	powerMotorLeft(stopmoving);
	powerMotorRight(stopmoving);

}

void closeArm() {

	while(!isArmClosed()) {
		powerMotorLeft(close);
		powerMotorRight(close);
	}

	powerMotorLeft(stopmoving);
	powerMotorRight(stopmoving);

}

//Button functions for the controller

bool controllerOpen() {

	if(vexRT[Btn7D] == true) {return true;}
	else {return false;}

}

bool controllerClose() {

	if(vexRT[Btn7U] == true) {return true;}
	else {return false;}

}

//Arm button functions

bool isArmButtonPressed() {

	if(SensorValue[armButton] == true) 	{return true;}
	else																{return false;}

}

void buttonOperate() {

	if			(isArmOpen()) 	{closeArm();}
	else										{openArm();}

}

//Main task

task main()
{

	startTask(display);

	while(robotMode == noMode) {wait1Msec(100);}

	while(true) {

		while(robotMode == controller) {
				if(controllerOpen()) {
					openArm();
				}
				else if(controllerClose()) {
					closeArm();
				}
		}

		while(robotMode == demo) {
				openArm();
				wait1Msec(10000);
				closeArm();
				wait1Msec(10000);
		}

		while(robotMode == button) {
				if(isArmButtonPressed()) {
					buttonOperate();
				}
		}

	} //end of while(true)

}

//LCD Display screen task

task display() {

	robotMode = noMode;

	//Start-up splash screen

	bLCDBacklight = true;
	clearLCD();

	displayLCDString(0, 0, "Matt&RyanBallou");
	displayLCDString(1, 0, "2018ScienceFair");

	wait1Msec(3000); //wait 3sec
	clearLCD();

	wait1Msec(100);

	clearLCD();
	displayLCDString(0, 0, "SELECT MODE");
	displayLCDString(1, 0, "BTTN  CTRL  DEMO");


	while(true) {

	if			((nLCDButtons) == left) 	{robotMode = button; clearLCD(); 			displayLCDString(0, 0, "BTN MODE"); 	displayLCDString(1, 0, "BTTN  CTRL  DEMO");}
	else if	((nLCDButtons) == center) {robotMode = controller; clearLCD(); 	displayLCDString(0, 0, "CTRL MODE"); 	displayLCDString(1, 0, "BTTN  CTRL  DEMO");}
	else if	((nLCDButtons) == right) 	{robotMode = demo; clearLCD(); 				displayLCDString(0, 0, "DEMO MODE"); 	displayLCDString(1, 0, "BTTN  CTRL  DEMO");}

	}

}
